# Get config

In [1]:
run configs/lf_disc_config.py

ERROR:root:File `'configs/lf_disc_config.py'` not found.


In [5]:
from configs import get_config, get_lf_disc_lstm_config

In [6]:
config = get_lf_disc_lstm_config()

# Dataset 

In [15]:
from glob import glob

In [16]:
glob('visdial/data/*')

['visdial/data/readers.py',
 'visdial/data/augment.py',
 'visdial/data/dataset.py',
 'visdial/data/vocabulary.py',
 'visdial/data/__pycache__',
 'visdial/data/__init__.py']

In [7]:
run visdial/data/dataset.py

In [8]:
dataset = VisDialDataset(config, 'train')

  5%|▌         | 2478/45238 [00:00<00:03, 12239.88it/s]

[val2018] Tokenizing questions...


  8%|▊         | 2628/34822 [00:00<00:02, 13193.41it/s]

[val2018] Tokenizing answers...


100%|██████████| 2064/2064 [00:00<00:00, 11011.64it/s]

[val2018] Tokenizing captions...


In [9]:
run visdial/data/readers.py

In [12]:
split = 'train'

In [13]:
split

'train'

In [14]:
config['dataset'][split]

{'path_feat_img': '/home/quanguet/datasets/visdial/features_faster_rcnn_x101_val.h5',
 'path_json_dialogs': '/home/quanguet/datasets/visdial/visdial_1.0_val.json',
 'path_json_word_count': '/home/quanguet/datasets/visdial/visdial_1.0_word_counts_train.json',
 'path_json_dense_dialogs': '/home/quanguet/datasets/visdial/'}

In [10]:
reader = DialogsReader(config, 'train')

  3%|▎         | 1285/45238 [00:00<00:03, 12846.18it/s]

[val2018] Tokenizing questions...


  3%|▎         | 1218/34822 [00:00<00:02, 12171.07it/s]

[val2018] Tokenizing answers...


 46%|████▌     | 954/2064 [00:00<00:00, 9534.24it/s]

[val2018] Tokenizing captions...


100%|██████████| 2064/2064 [00:00<00:00, 9786.85it/s]


In [5]:
img_ids = dataset.image_ids
img_id = img_ids[0]

In [66]:
len(dataset.tokenizer)

11322

In [50]:
def untokenize(ids):
    "ids: numpy array"
    tokens = " ".join(dataset.tokenizer.convert_ids_to_tokens(ids))
    tokens = tokens.replace('<PAD>', ' ')
    return tokens

In [51]:
for key in sample:
    print(key, sample[key].shape)

img_ids torch.Size([])
num_rounds torch.Size([])
opts torch.Size([10, 100, 25])
opts_in torch.Size([10, 100, 25])
opts_out torch.Size([10, 100, 25])
opts_len torch.Size([10, 100])
opts_in_len torch.Size([10, 100])
opts_out_len torch.Size([10, 100])
ans torch.Size([10, 25])
ans_in torch.Size([10, 25])
ans_out torch.Size([10, 25])
ans_len torch.Size([10])
ans_in_len torch.Size([10])
ans_out_len torch.Size([10])
ans_ind torch.Size([10])
gt_relevance torch.Size([100])
round_id torch.Size([])
img_feat torch.Size([36, 2048])
ques_tokens torch.Size([10, 25])
hist_tokens torch.Size([10, 10, 50])
ques_len torch.Size([10])
hist_len torch.Size([10, 10])


# Check answer options 

In [56]:
import random
idx = random.randint(1,9)

print(sample['opts_len'].shape)
print(sample['opts'].shape)

print(sample['opts_len'][idx][:10])
for ids in sample['opts'][idx][:10]:
    print(untokenize(ids.numpy()))

torch.Size([10, 100])
torch.Size([10, 100, 25])
tensor([16, 10,  3, 13,  3,  7,  4,  4,  6,  8])
not too old , but any time within the past thirty or so years is possible                  
it might be , its some kind of formal event                              
1 is young                                            
i can not see a collar because of how the cat is laying                        
part of it                                            
i see no humans in the picture                                    
yes a gas range                                          
black brown and white                                          
gray , black , and white                                      
it 's blurry but like silver and bluish                                  


In [57]:
import random
idx = random.randint(1,9)
print('idx =',idx)
print(sample['opts_in_len'].shape)
print(sample['opts_in'].shape)

print(sample['opts_in_len'][idx][:10])
for ids in sample['opts_in'][idx][:10]:
    print(untokenize(ids.numpy()))

idx = 8
torch.Size([10, 100])
torch.Size([10, 100, 25])
tensor([2, 2, 4, 3, 5, 2, 4, 5, 3, 7])
<S> brown                                              
<S> blue                                              
<S> i think so                                          
<S> not sure                                            
<S> yes , it is                                        
<S> 4                                              
<S> wood and wire                                          
<S> looks like a stone                                        
<S> a plate                                            
<S> black , brown , and white                                    


In [58]:
import random
idx = random.randint(1,9)
print('idx =',idx)

print(sample['opts_out_len'].shape)
print(sample['opts_out'].shape)

print(sample['opts_out_len'][idx][:10])
for ids in sample['opts_out'][idx][:10]:
    print(untokenize(ids.numpy()))

idx = 5
torch.Size([10, 100])
torch.Size([10, 100, 25])
tensor([2, 6, 2, 2, 2, 5, 2, 2, 3, 9])
0 </S>                                              
not that i can see </S>                                      
1 </S>                                              
red </S>                                              
maybe </S>                                              
yes , it is </S>                                        
4 </S>                                              
fairly </S>                                              
no way </S>                                            
no , it is lit by the sun </S>                                


# Check ground truth answer 

In [59]:
print(sample['ans_len'].shape)
print(sample['ans'].shape)

print(sample['ans_len'])
for ids in sample['ans']:
    print(untokenize(ids.numpy()))

torch.Size([10])
torch.Size([10, 25])
tensor([1, 1, 1, 5, 1, 1, 3, 1, 4, 1])
yes                                                
no                                                
no                                                
i do n't see windows                                        
maybe                                                
no                                                
no not really                                            
yes                                                
cheap plastic or wood                                          
yes                                                


In [60]:
print(sample['ans_in_len'].shape)
print(sample['ans_in'].shape)

print(sample['ans_in_len'])
for ids in sample['ans_in']:
    print(untokenize(ids.numpy()))

torch.Size([10])
torch.Size([10, 25])
tensor([2, 2, 2, 6, 2, 2, 4, 2, 5, 2])
<S> yes                                              
<S> no                                              
<S> no                                              
<S> i do n't see windows                                      
<S> maybe                                              
<S> no                                              
<S> no not really                                          
<S> yes                                              
<S> cheap plastic or wood                                        
<S> yes                                              


In [61]:
print(sample['ans_out_len'].shape)
print(sample['ans_out'].shape)

print(sample['ans_out_len'])
for ids in sample['ans_out']:
    print(untokenize(ids.numpy()))

torch.Size([10])
torch.Size([10, 25])
tensor([2, 2, 2, 6, 2, 2, 4, 2, 5, 2])
yes </S>                                              
no </S>                                              
no </S>                                              
i do n't see windows </S>                                      
maybe </S>                                              
no </S>                                              
no not really </S>                                          
yes </S>                                              
cheap plastic or wood </S>                                        
yes </S>                                              


# Check history 

In [63]:
for hist_id in range(10):
    print(sample['hist_len'][hist_id])
    for i, ids in enumerate(sample['hist_tokens'][hist_id]):
        print(i + 1, untokenize(ids.numpy()))
    print("------")

tensor([13.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])
1 a bedroom is filled with lots of posters and a busy computer desk                                                                          
2                                                                                                    
3                                                                                                    
4                                                                                                    
5                                                                                                    
6                                                                                                    
7                                                                                                    
8                                                                                                    
9                                                                                    

# Check questions

In [64]:
print(sample['ques_tokens'].shape)
for ques in sample['ques_tokens']:
    print(untokenize(ques.numpy()))

torch.Size([10, 25])
is the photo in color ?                                      
is it a professional photo ?                                      
is it well lit ?                                        
is it daytime ?                                          
does this look like an adults bedroom ?                                  
is the room clean ?                                        
can you tell what kind of computer it is ?                              
is it a flat screen ?                                      
what 's the desk made out of ?                                  
is there a computer chair ?                                      


In [68]:
sample['ques_tokens'].shape

torch.Size([10, 25])

In [69]:
sample['ques_len']

tensor([ 6,  6,  5,  4,  8,  5, 10,  6,  8,  6])

In [70]:
torch.arange(sample['ques_len'])[None, :] < lens[:, None]

TypeError: arange(): argument 'end' (position 1) must be Number, not Tensor

In [77]:
max_len = config['dataset']['max_seq_len']

ques_mask = torch.arange(max_len).expand(10, max_len) < sample['ques_len'].unsqueeze(1)

In [79]:
import torch.nn as nn

In [90]:
nn.Embedding(11322, 300)(sample['ques_tokens'].unsqueeze(0).unsqueeze(0)).shape

torch.Size([1, 1, 10, 25, 300])

In [87]:
nn.Embedding(11322, 300)(sample['hist_tokens'].long().unsqueeze(0))[0]

tensor([[[[ 2.4683, -2.6338,  0.0755,  ...,  0.9948,  0.4302, -0.9629],
          [-0.2713, -0.4015, -0.7374,  ..., -1.4742, -1.6325,  1.0094],
          [-1.8145,  0.9618,  1.4725,  ..., -0.3751,  1.3166,  0.8320],
          ...,
          [ 0.3491,  0.4476, -0.5386,  ..., -0.3255,  0.3490, -0.9946],
          [ 0.3491,  0.4476, -0.5386,  ..., -0.3255,  0.3490, -0.9946],
          [ 0.3491,  0.4476, -0.5386,  ..., -0.3255,  0.3490, -0.9946]],

         [[ 0.3491,  0.4476, -0.5386,  ..., -0.3255,  0.3490, -0.9946],
          [ 0.3491,  0.4476, -0.5386,  ..., -0.3255,  0.3490, -0.9946],
          [ 0.3491,  0.4476, -0.5386,  ..., -0.3255,  0.3490, -0.9946],
          ...,
          [ 0.3491,  0.4476, -0.5386,  ..., -0.3255,  0.3490, -0.9946],
          [ 0.3491,  0.4476, -0.5386,  ..., -0.3255,  0.3490, -0.9946],
          [ 0.3491,  0.4476, -0.5386,  ..., -0.3255,  0.3490, -0.9946]],

         [[ 0.3491,  0.4476, -0.5386,  ..., -0.3255,  0.3490, -0.9946],
          [ 0.3491,  0.4476, -

In [100]:
x = torch.randn((1, 2, 3), device='cuda:0')
x.new_ones((2, 3), dtype=torch.long)

tensor([[1, 1, 1],
        [1, 1, 1]], device='cuda:0')

In [93]:
nn.LSTM(100, 100)(torch.randn(1*2, 3, 100))

AttributeError: 'tuple' object has no attribute 'shape'